In [31]:
sites = [
"GAGGTAAAC",
"TCCGTAAGC",
"CAGGTTGGA",
"ACAGTCAGC",
"TAGGTCAGC",
"CAGGTCAGC",
"CAGGTCGAT",
"CAGGTCAGC",
"CAGGTCAGC",
"CAGGTTGGC"
]

In [32]:
import numpy as np

al = ['A', 'T', 'G', 'C']
index = {n:i for i,n in enumerate(al)}

def create_pfm(sites):
    L = len(sites[0])
    pfm = np.zeros((4, L))

    for s in sites:
        for pos, nuc in enumerate(s):
            pfm[index[nuc], pos] += 1

    return pfm

pfm = create_pfm(sites)
print(pfm)

[[ 1.  8.  1.  0.  0.  2.  7.  2.  1.]
 [ 2.  0.  0.  0. 10.  2.  0.  0.  1.]
 [ 1.  0.  8. 10.  0.  0.  3.  8.  0.]
 [ 6.  2.  1.  0.  0.  6.  0.  0.  8.]]


In [33]:
def convert_to_ppm(pfm, alpha=0.1):
    N = pfm.sum(axis=0)[0] 
    ppm = (pfm + alpha) / (N + 4*alpha)
    return ppm

ppm = convert_to_ppm(pfm)
print(ppm)

[[0.10576923 0.77884615 0.10576923 0.00961538 0.00961538 0.20192308
  0.68269231 0.20192308 0.10576923]
 [0.20192308 0.00961538 0.00961538 0.00961538 0.97115385 0.20192308
  0.00961538 0.00961538 0.10576923]
 [0.10576923 0.00961538 0.77884615 0.97115385 0.00961538 0.00961538
  0.29807692 0.77884615 0.00961538]
 [0.58653846 0.20192308 0.10576923 0.00961538 0.00961538 0.58653846
  0.00961538 0.00961538 0.77884615]]


In [34]:
bg = np.array([0.295, 0.295, 0.205, 0.205]).reshape(4,1)

def calculate_pwm(ppm, bg):
    pwm = np.log2(ppm / bg)
    return pwm

pwm = calculate_pwm(ppm, bg)
print(pwm)

[[-1.47979496  1.40062343 -1.47979496 -4.93922658 -4.93922658 -0.54690915
   1.21052054 -0.54690915 -1.47979496]
 [-0.54690915 -4.93922658 -4.93922658 -4.93922658  1.71898491 -0.54690915
  -4.93922658 -4.93922658 -1.47979496]
 [-0.95470391 -4.41413553  1.92571447  2.24407595 -4.41413553 -4.41413553
   0.54006078  1.92571447 -4.41413553]
 [ 1.5166018  -0.02181811 -0.95470391 -4.41413553 -4.41413553  1.5166018
  -4.41413553 -4.41413553  1.92571447]]


In [35]:
def max_score(pwm):
    return pwm.max(axis=0).sum()

def min_score(pwm):
    return pwm.min(axis=0).sum()

print("max score =", max_score(pwm))
print("min score =", min_score(pwm))

max score = 15.384551840581208
min score = -39.943425491429075


In [36]:
def best_seq(pwm, al):
    seq = ""
    for i in range(pwm.shape[1]):
        idx = np.argmax(pwm[:, i])
        seq += al[idx]
    return seq

print(best_seq(pwm, al))

CAGGTCAGC


In [37]:
def worst_seq(pwm, al):
    seq = ""
    for i in range(pwm.shape[1]):
        idx = np.argmin(pwm[:, i])
        seq += al[idx]
    return seq

print(worst_seq(pwm, al))

ATTAAGTTG
