In [24]:
from Bio import SeqIO
import numpy as np
import matplotlib.pyplot as plt

records = SeqIO.parse("chr1.fa", "fasta")
record = next(records)
genome = record.seq
seq = genome[:1_000_000]

In [5]:
nucleotides = ['A', 'T', 'G', 'C']
index = {nuc: i for i, nuc in enumerate(nucleotides)}

In [6]:
dinuc_counts = np.zeros((4, 4), dtype=int)
for i in range(len(seq) - 1):
    a, b = seq[i], seq[i+1]
    if a in nucleotides and b in nucleotides:
        dinuc_counts[index[a], index[b]] += 1

In [7]:
print("Частоты динуклеотидов (матрица счетов):")
print(dinuc_counts)

Частоты динуклеотидов (матрица счетов):
[[76770 55624 61373 45670]
 [45605 61806 60457 49199]
 [51537 40356 55009 43560]
 [65525 59282 13622 54601]]


In [8]:
transition_matrix = dinuc_counts / dinuc_counts.sum(axis=1, keepdims=True)

In [29]:
print("\nМатрица переходов (Pij):")
print(np.round(transition_matrix, 4))


Матрица переходов (Pij):
[[0.3206 0.2323 0.2563 0.1907]
 [0.2101 0.2847 0.2785 0.2267]
 [0.2706 0.2119 0.2888 0.2287]
 [0.3395 0.3071 0.0706 0.2829]]


In [18]:
transition_matrix

array([[0.32062714, 0.23231163, 0.25632212, 0.19073911],
       [0.21009642, 0.28473236, 0.27851769, 0.22665352],
       [0.27058941, 0.21188479, 0.28881877, 0.22870704],
       [0.33945501, 0.30711288, 0.07056934, 0.28286277]])

In [30]:
row_sums = transition_matrix.sum(axis=1)
print("\nСумма строк матрицы переходов (должна быть 1):")
print(np.round(row_sums, 4))


Сумма строк матрицы переходов (должна быть 1):
[1. 1. 1. 1.]


In [12]:
eigvals, eigvecs = np.linalg.eig(transition_matrix.T)
stationary = np.real(eigvecs[:, np.isclose(eigvals, 1)])
stationary = stationary / stationary.sum()  
stationary = stationary.flatten()

In [31]:
print("\nСтационарное распределение")
for nuc, freq in zip(nucleotides, stationary):
    print(f"{nuc}: {freq:.4f}")


Стационарное распределение
A: 0.2850
T: 0.2584
G: 0.2267
C: 0.2298


In [32]:
obs_counts = np.array([seq.count(nuc) for nuc in nucleotides])
obs_freq = obs_counts / obs_counts.sum()
print("\nНаблюдаемые частоты нуклеотидов:")
for nuc, freq in zip(nucleotides, obs_freq):
    print(f"{nuc}: {freq:.4f}")


Наблюдаемые частоты нуклеотидов:
A: 0.2850
T: 0.2584
G: 0.2267
C: 0.2298


In [33]:
print("\nСравнение стационарного распределения с наблюдаемыми частотами:")
for nuc, s, o in zip(nucleotides, stationary, obs_freq):
    print(f"{nuc}: π={s:.4f}, наблюдаемая={o:.4f}")


Сравнение стационарного распределения с наблюдаемыми частотами:
A: π=0.2850, наблюдаемая=0.2850
T: π=0.2584, наблюдаемая=0.2584
G: π=0.2267, наблюдаемая=0.2267
C: π=0.2298, наблюдаемая=0.2298
