### Задание 6

In [34]:
P = transition_matrix

In [35]:
P_prev = P.copy()
P_k = P.copy()  
norm_diff = []
for k in range(2, 1001):
    P_k = P_k @ P  
    diff = np.linalg.norm(P_k - P_prev, ord='fro')
    norm_diff.append(diff)
    P_prev = P_k.copy()

In [36]:
plt.figure(figsize=(10,5))
plt.plot(range(2, 1001), norm_diff)
plt.xlabel('k (степень матрицы)')
plt.ylabel('||P^k - P^(k-1)||_F')
plt.title('Сходимость P^k к стационарной матрице')
plt.grid(True)
plt.show()

In [37]:
P_1000 = np.linalg.matrix_power(P, 1000)
print("Матрица P^1000 (для демонстрации сходимости):")
print(np.round(P_1000, 4))

Матрица P^1000 (для демонстрации сходимости):
[[0.285  0.2584 0.2267 0.2298]
 [0.285  0.2584 0.2267 0.2298]
 [0.285  0.2584 0.2267 0.2298]
 [0.285  0.2584 0.2267 0.2298]]


In [38]:
print("\nСравнение строк P^1000 с π:")
for i, row in enumerate(P_1000):
    print(f"Строка {i}: {np.round(row, 4)}")
print("\nСтационарное распределение π:")
print(np.round(stationary, 4))


Сравнение строк P^1000 с π:
Строка 0: [0.285  0.2584 0.2267 0.2298]
Строка 1: [0.285  0.2584 0.2267 0.2298]
Строка 2: [0.285  0.2584 0.2267 0.2298]
Строка 3: [0.285  0.2584 0.2267 0.2298]

Стационарное распределение π:
[0.285  0.2584 0.2267 0.2298]
